{
 "title": "Netology",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "CPU load",
   "type": "graph",
   "description": "Утилизация CPU для nodeexporter (в процентах, 100-idle)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by(instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[$__rate_interval])) * 100)",
     "legendFormat": "CPU load"
    }
   ]
  },
  {
   "title": "Load averege",
   "type": "graph",
   "description": "CPULA 1/5/15",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=\"nodeexporter:9100\"}",
     "legendFormat": "LA 1 min"
    },
    {
     "expr": "node_load5{instance=\"nodeexporter:9100\"}",
     "legendFormat": "LA 10 min"
    },
    {
     "expr": "node_load15{instance=\"nodeexporter:9100\"}",
     "legendFormat": "LA 15 min"
    }
   ]
  },
  {
   "title": "Free RAM",
   "type": "graph",
   "description": "Количество места на файловой системе",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{instance=\"nodeexporter:9100\"}",
     "legendFormat": "Free RAM"
    }
   ]
  },
  {
   "title": "Free space",
   "type": "graph",
   "description": "Количество свободной оперативной памяти",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(mountpoint) (node_filesystem_avail_bytes{mountpoint=~\"/\"})",
     "legendFormat": "/"
    }
   ]
  }
 ]
}