---
- name: Restart clickhouse service
  become: true
  ansible.builtin.service:
    name: clickhouse-server
    state: restarted

- name: Restart nginx service
  become: true
  ansible.builtin.systemd:
    name: nginx
    state: restarted

- name: Restart vector service
  become: true
  ansible.builtin.systemd:
    name: vector
    state: restarted
