---
- name: Get OpenJDK installed
  hosts: sonarqube
  pre_tasks:
    - name: install unzip
      become: true
      yum:
        name: unzip
        state: present
  tasks:
    - name: Upload .tar.gz file conaining binaries from remote storage
      get_url:
        url: "{{ jdk_url }}"
        dest: "/tmp/jdk-{{ jdk_distr_name }}"
        mode: 0755
      register: download_java_remote_binaries
      until: download_java_remote_binaries is succeeded

    - name: Ensure installation dir exists
      become: true
      file:
        state: directory
        path: "{{ java_home }}"
        mode: 0755

    - name: Extract java in the installation directory
      become: true
      unarchive:
        copy: false
        src: "/tmp/jdk-{{ jdk_distr_name }}"
        dest: "{{ java_home }}"
        extra_opts: [--strip-components=1]
        creates: "{{ java_home }}/bin/java"

    - name: Export environment variables
      become: true
      template:
        src: jdk.sh.j2
        dest: /etc/profile.d/jdk.sh
        owner: root
        group: root
        mode: 0644
